export const FETCH_QUIZ_PENDING = "FETCH_QUIZ_PENDING";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";

export default [FETCH_QUIZ_SUCCESS, FETCH_QUIZ_FAILURE, FETCH_QUIZ_PENDING];
